// =============================================================
// Daily PDF report
// Today's daily_logs + delays → Gemini summary (via Edge Function) → html2pdf
// =============================================================
import { MANPOWER_TRADES } from './config.js';

const SUMMARY_FUNCTION = 'daily-summary';

// ---------- Helpers ----------
function todayRange() {
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const end = new Date(start);
  end.setDate(end.getDate() + 1);
  return {
    date: start.toLocaleDateString('en-CA'), // YYYY-MM-DD, local time
    startISO: start.toISOString(),
    endISO: end.toISOString(),
  };
}

const longDate = (iso) => new Date(`${iso}T00:00`).toLocaleDateString(undefined, {
  weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
});

const tradeLabel = (key) => MANPOWER_TRADES.find((t) => t.key === key)?.label ?? key.replace(/_/g, ' ');

const flatLabel = (flat) => (flat ? `Block ${flat.block} · Flat ${flat.flat_number}` : 'Site-wide');

function mergeManpower(logs) {
  const totals = {};
  for (const log of logs) {
    for (const [trade, count] of Object.entries(log.manpower || {})) {
      totals[trade] = (totals[trade] || 0) + Number(count || 0);
    }
  }
  return Object.entries(totals).filter(([, n]) => n > 0);
}

// ---------- 1. Query today's data ----------
async function fetchTodayData(db, projectId, day) {
  const [logs, delays] = await Promise.all([
    db.from('daily_logs')
      .select('log_date, weather, manpower, notes')
      .eq('project_id', projectId)
      .eq('log_date', day.date),
    db.from('delays')
      .select('delay_cause, duration_hours, description, created_at, flats(block, floor, flat_number)')
      .eq('project_id', projectId)
      .gte('created_at', day.startISO)
      .lt('created_at', day.endISO)
      .order('created_at'),
  ]);

  const failed = [logs, delays].find((r) => r.error);
  if (failed) throw new Error(`Could not load today's data: ${failed.error.message}`);
  return { logs: logs.data, delays: delays.data };
}

// ---------- 2. AI summary ----------
async function fetchSummary(db, payload) {
  if (!payload.daily_logs.length && !payload.delays.length) {
    return { bullets: ['No daily log or delays were recorded for this project today.'], source: 'none' };
  }

  const { data, error } = await db.functions.invoke(SUMMARY_FUNCTION, { body: payload });
  if (error) {
    let message = error.message;
    try {
      const body = await error.context?.json();
      if (body?.error) message = body.error;
    } catch { /* non-JSON error body */ }
    return { bullets: [], source: 'error', note: `AI summary unavailable: ${message}` };
  }
  return { bullets: data.bullets ?? [], source: 'ai' };
}

// ---------- 3. Populate the printable template ----------
function addRow(tbody, cells) {
  const tr = document.createElement('tr');
  for (const { text, className } of cells) {
    const td = document.createElement('td');
    td.textContent = text;
    if (className) td.className = className;
    tr.appendChild(td);
  }
  tbody.appendChild(tr);
}

function addEmptyRow(tbody, colspan, text) {
  const tr = document.createElement('tr');
  const td = document.createElement('td');
  td.colSpan = colspan;
  td.className = 'pdf-empty';
  td.textContent = text;
  tr.appendChild(td);
  tbody.appendChild(tr);
}

function buildReport({ project, day, logs, delays, manpower, summary, userEmail }) {
  const page = document.getElementById('daily-report-template').content.firstElementChild.cloneNode(true);
  const set = (field, value) => { page.querySelector(`[data-field="${field}"]`).textContent = value; };

  // Site details
  const workers = manpower.reduce((sum, [, n]) => sum + n, 0);
  const hoursLost = delays.reduce((sum, d) => sum + Number(d.duration_hours || 0), 0);
  const weather = [...new Set(logs.map((l) => l.weather).filter(Boolean))].join(', ');

  set('project', project.name);
  set('location', project.location || '');
  set('date', longDate(day.date));
  set('weather', weather || 'Not recorded');
  set('manpower-total', workers);
  set('delay-count', delays.length);
  set('delay-hours', hoursLost.toLocaleString());
  set('total-flats', project.total_flats ?? '—');

  // Executive summary
  const list = page.querySelector('[data-list="summary"]');
  for (const bullet of summary.bullets) {
    const li = document.createElement('li');
    li.textContent = bullet;
    list.appendChild(li);
  }
  set('summary-note', {
    ai: 'AI-generated by Gemini from the log and delay entries in this report.',
    error: summary.note,
    none: '',
  }[summary.source]);

  // Manpower
  const mpRows = page.querySelector('[data-rows="manpower"]');
  if (manpower.length) {
    manpower.forEach(([trade, n]) => addRow(mpRows, [{ text: tradeLabel(trade) }, { text: n, className: 'num' }]));
    addRow(mpRows, [{ text: 'Total', className: 'pdf-strong' }, { text: workers, className: 'num pdf-strong' }]);
  } else {
    addEmptyRow(mpRows, 2, 'No manpower recorded.');
  }

  // Delays
  const delayRows = page.querySelector('[data-rows="delays"]');
  if (delays.length) {
    delays.forEach((d) => addRow(delayRows, [
      { text: d.delay_cause },
      { text: flatLabel(d.flats) },
      { text: Number(d.duration_hours).toLocaleString(), className: 'num' },
      { text: d.description || '—' },
    ]));
  } else {
    addEmptyRow(delayRows, 4, 'No delays recorded today.');
  }

  // Notes + footer
  set('notes', logs.map((l) => l.notes).filter(Boolean).join('\n\n') || 'No site notes recorded.');
  set('generated', `Generated ${new Date().toLocaleString()}${userEmail ? ` by ${userEmail}` : ''}`);

  return page;
}

// ---------- 4. Export ----------
/**
 * Builds today's report for `project` and downloads Daily_Report_[YYYY-MM-DD].pdf.
 * Returns { aiNote } — set when the PDF was saved without an AI summary.
 */
export async function generateDailyReport({ db, project, userEmail }) {
  const day = todayRange();
  const { logs, delays } = await fetchTodayData(db, project.id, day);
  const manpower = mergeManpower(logs);

  const summary = await fetchSummary(db, {
    date: day.date,
    project: { name: project.name, location: project.location, total_flats: project.total_flats },
    daily_logs: logs.map((l) => ({ weather: l.weather, notes: l.notes })),
    manpower: Object.fromEntries(manpower.map(([trade, n]) => [tradeLabel(trade), n])),
    delays: delays.map((d) => ({
      cause: d.delay_cause,
      location: flatLabel(d.flats),
      duration_hours: Number(d.duration_hours),
      description: d.description,
    })),
  });

  const page = buildReport({ project, day, logs, delays, manpower, summary, userEmail });
  const root = document.getElementById('pdf-export-root');
  root.replaceChildren(page);

  try {
    await window.html2pdf()
      .set({
        margin: [10, 10, 12, 10], // mm: top, right, bottom, left
        filename: `Daily_Report_${day.date}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff' },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'], avoid: ['tr', '.pdf-avoid-break'] },
      })
      .from(page)
      .save();
  } finally {
    root.replaceChildren();
  }

  return { aiNote: summary.source === 'error' ? summary.note : null };
}
